FROM node:alpine as builder

RUN cd home \
    && mkdir app

RUN chmod -R 777 /home/app

WORKDIR home/app

COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000 
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/app/build  /usr/share/nginx/html