    # 권한 설정 : 관리자 권한
    sudo: required

    # 언어 설정 : generic
    language: generic

    # 필요한 서비스 설정 : 도커환경이므로, docker 설정
    services:
        - docker

    # 스크립트를 실행하기 위한 환경 구성
    # 도커이미지 만들기
    before_install:
        - echo "start Creating an image with dockerfile"
        - docker build -t devscof/docker-react-app -f dockerfile.dev ./

    # 실행할 스크립트(테스트) 설정
    # -e CI=true 는 Travis CI를 사용하기 위한 환경변수
    script:
        - docker run -e CI=true devscof/docker-react-app npm run test -- --coverage

    # 스크립트(테스트)가 성공한 이후 할 일 설정
    after_success:
        - echo "Test Success"