# 베이스 이미지 설정
FROM node:alpine

# ./을 /usr/src/app으로 설정
WORKDIR /usr/src/app

# package.json을 ./으로 복사
COPY package.json ./

# 종속성 다운로드
RUN npm install

# ./으로 복사
COPY ./ ./

# 실행 명령 추가
CMD ["npm", "run", "start"]